FROM node:20-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-workspace.yaml ./
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/hub ./apps/hub
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
ENV WS_PORT=3003
RUN npm install -g pnpm
RUN pnpm install
RUN pnpm db:generate

RUN cd apps/hub && pnpm run build
EXPOSE 3003

ENV NODE_ENV=production


CMD ["pnpm", "run", "start:hub"]