name: deploy the API
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.api
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pingchain-api:${{ github.sha }}
          build-args: |
           DATABASE_URL=${{ secrets.DATABASE_URL }}
      - name: Deploy to VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key admin@${{ secrets.VM_IP }} -t "docker pull ${{ secrets.DOCKER_USERNAME }}/pingchain-api:${{ github.sha }} && docker stop pingchain-api && docker rm pingchain-api && docker run --name pingchain-api -d -p 3002:3002 ${{ secrets.DOCKER_USERNAME }}/pingchain-api:${{ github.sha }}"

  