name: deploy the frontend
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pingchain-frontend:${{ github.sha }}
          build-args: |
           CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}
           CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
           EXPRESS_BACKEND_URL=${{ secrets.EXPRESS_BACKEND_URL }}
           WS_URL=${{ secrets.WS_URL }}
           DATABASE_URL=${{ secrets.DATABASE_URL }}
      - name: Deploy to VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key admin@${{ secrets.VM_IP }} -t "docker pull ${{ secrets.DOCKER_USERNAME }}/pingchain-frontend:${{ github.sha }} && docker stop pingchain-frontend && docker rm pingchain-frontend && docker run --name pingchain-frontend -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/pingchain-frontend:${{ github.sha }}"
      
